# Configuration for Gitlab-CI.

image: tpetazzoni/toolchain-builder-build:202407162158

build-job:
  stage: build
  script:
    - mkdir -p build/plop/machin/truc/bidule
    - touch build/plop/machin/truc/bidule/chose.txt

