# Configuration for Gitlab-CI.
# Builds appear on https://gitlab.com/kubu93/toolchains-builder/pipelines

image: $CI_REGISTRY/buildroot.org/buildroot/base:20230207.1123

stages:
  - generate-gitlab-ci
  - build

generate-gitlab-ci-yml:
  stage: generate-gitlab-ci
  script: .gitlab-ci/generate-gitlab-ci-yml .gitlab-ci/gitlab-ci.yml.in > generated-gitlab-ci.yml
  artifacts:
    paths:
      - generated-gitlab-ci.yml

buildroot-pipeline:
  stage: build
  trigger:
    include:
      - artifact: generated-gitlab-ci.yml
        job: generate-gitlab-ci-yml
    strategy: depend
