#!/bin/sh

case "$1" in
    start)
    echo "Starting tests"
    echo "TODO: add some more tests"
    sleep 2
    echo "Ending tests"
    ;;
    *)
    echo "This is the toolchain test suite"
    echo "Usage: $0 start"
    exit 1
esac

exit $?
